version: '3'

services:
  app:
    build: .
    #entrypoint: ./.docker/entrypoint.sh
    container_name: node-base-project-app
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
